n1 = int(input("give me the first number: "))
n2 = int(input("give me the second number: "))
print(F"thank you")
print(f" {n1} + {n2} = {n1 + n2}")
print(f" {n1} - {n2} = {n1 - n2}")
print(f" {n1} / {n2} = {n1 / n2}")
print(f" {n1} * {n2} = {n1 * n2}")
